version = 0.1
[default.deploy.parameters]
stack_name = "dynamoapp-stack"
resolve_s3 = true
s3_prefix = "dynamoapp-stack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
